### ISSUE TITLE
Error to sync a ftp2 server

### ISSUE THREAD

**Issue by guisz1** [mar10/pyftpsync#54]
the return error is the command MLDS nos is valid, the 4.0 resolve this?
```
INFO:keyring.backend:Loading KWallet
INFO:keyring.backend:Loading SecretService
INFO:keyring.backend:Loading Windows
INFO:keyring.backend:Loading chainer
INFO:keyring.backend:Loading macOS
INFO:pyftpsync:Download to /home/guilherme.zulian/teste
                from ftp://200.201.27.44/
INFO:pyftpsync:Encoding local: utf-8, remote: utf-8
INFO:pyftpsync:Setting FTP encoding to utf-8 (was latin-1).
ERROR:pyftpsync:Could not write lock file: 553 Could not create file.
Traceback (most recent call last):
  File "/home/guilherme.zulian/.local/lib/python3.8/site-packages/ftpsync/ftp_target.py", line 514, in get_dir
    self._ftp_retrlines_native("MLSD", _addline, encoding)
  File "/home/guilherme.zulian/.local/lib/python3.8/site-packages/ftpsync/ftp_target.py", line 772, in _ftp_retrlines_native
    self.ftp.retrbinary(command, _on_read_chunk)
  File "/usr/lib/python3.8/ftplib.py", line 425, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/usr/lib/python3.8/ftplib.py", line 382, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/lib/python3.8/ftplib.py", line 348, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "/usr/lib/python3.8/ftplib.py", line 275, in sendcmd
    return self.getresp()
  File "/usr/lib/python3.8/ftplib.py", line 248, in getresp
    raise error_perm(resp)
ftplib.error_perm: 500 Unknown command.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "t.py", line 11, in <module>
    s.run()
  File "/home/guilherme.zulian/.local/lib/python3.8/site-packages/ftpsync/synchronizers.py", line 1268, in run
    res = super(DownloadSynchronizer, self).run()
  File "/home/guilherme.zulian/.local/lib/python3.8/site-packages/ftpsync/synchronizers.py", line 827, in run
    res = super(BiDirSynchronizer, self).run()
  File "/home/guilherme.zulian/.local/lib/python3.8/site-packages/ftpsync/synchronizers.py", line 213, in run
    res = self._sync_dir()
  File "/home/guilherme.zulian/.local/lib/python3.8/site-packages/ftpsync/synchronizers.py", line 485, in _sync_dir
    remote_entries = self.remote.get_dir()
  File "/home/guilherme.zulian/.local/lib/python3.8/site-packages/ftpsync/ftp_target.py", line 520, in get_dir
    raise RuntimeError(
RuntimeError: The FTP server does not support the 'MLSD' command.

```

**Comment by mar10** [comment]
FTP(S)  will still require the MLSD command. However version 4.0 adds support for the SFTP protocol.
