### ISSUE TITLE
Faild with FTP server with windows-1251 encoding

### ISSUE THREAD

**Issue by vgdh** [mar10/pyftpsync#65]
With code
```
from ftpsync.targets import FsTarget
from ftpsync.ftp_target import FtpTarget
from ftpsync.synchronizers import UploadSynchronizer
from ftpsync.synchronizers import DownloadSynchronizer
from ftpsync.synchronizers import BiDirSynchronizer
import ftpsync

import logging
import logging.handlers
from ftpsync.util import set_pyftpsync_logger

custom_logger = logging.getLogger("my.logger")
log_path = "D:\\TMP\\pyftpsync.log"
handler = logging.handlers.WatchedFileHandler(log_path)
formatter = logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
handler.setFormatter(formatter)
custom_logger.addHandler(handler)
set_pyftpsync_logger(custom_logger)

# import logging
# logger = logging.getLogger("pyftpsync")
# logger.setLevel(logging.DEBUG)

local = FsTarget("D:\\TMP\\ftpSync")
user = "blabla"
passwd = "blabla"

opts = {"encoding":"cp1251"}
remote = FtpTarget("/", "ftp.blabla.ru", username=user, password=passwd, extra_opts=opts)

opts = {"force": False, "delete_unmatched": True, "verbose": 6}
s = DownloadSynchronizer(local, remote, opts)
s.run()

```

**I get an error:**
```
INFO:my.logger:Encoding local: utf-8, remote: cp1251
Traceback (most recent call last):
  File "C:\Users\IR\PycharmProjects\untitled6\Sync_FTP.py", line 36, in <module>
    s.run()
  File "C:\Python39\lib\site-packages\ftpsync\synchronizers.py", line 1268, in run
    res = super(DownloadSynchronizer, self).run()
  File "C:\Python39\lib\site-packages\ftpsync\synchronizers.py", line 827, in run
    res = super(BiDirSynchronizer, self).run()
  File "C:\Python39\lib\site-packages\ftpsync\synchronizers.py", line 211, in run
    self.remote.open()
  File "C:\Python39\lib\site-packages\ftpsync\ftp_target.py", line 155, in open
    self.ftp.login(self.username, self.password)
  File "C:\Python39\lib\ftplib.py", line 407, in login
    resp = self.sendcmd('PASS ' + passwd)
  File "C:\Python39\lib\ftplib.py", line 279, in sendcmd
    return self.getresp()
  File "C:\Python39\lib\ftplib.py", line 242, in getresp
    resp = self.getmultiline()
  File "C:\Python39\lib\ftplib.py", line 228, in getmultiline
    line = self.getline()
  File "C:\Python39\lib\ftplib.py", line 210, in getline
    line = self.file.readline(self.maxline + 1)
  File "C:\Python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 4: invalid continuation byte
```

in codecs.py 
```
    def decode(self, input, final=False):
        # decode input (taking the buffer into account)
        data = self.buffer + input
        (result, consumed) = self._buffer_decode(data, self.errors, final)
        # keep undecoded input until the next call
        self.buffer = data[consumed:]
        return result

```

i have this data in input parameter:
**b'230-\xc4\xee\xe1\xf0\xee \xef\xee\xe6\xe0\xeb\xee\xe2\xe0\xf2\xfc  \xed\xe0 FTP \xf1\xe5\xf0\xe2\xe5\xf0 \xea\xee\xec\xef\xe0\xed\xe8\xe8 Maykor.\r\n230 User logged in, proceed.\r\n'**

What decode as:
**b'230-Добро пожаловать на FTP сервер компании Maykor.
230 User logged in, proceed.
'**

**Comment by mar10** [comment]
Would it work if you change this line
https://github.com/mar10/pyftpsync/blob/d71f347e63ab1f2bfeb922966f08f28ac2031a06/ftpsync/ftp_target.py#L84

to

```py
 self.ftp = ftplib.FTP(encoding=self.encoding)
```
?

**Comment by vgdh** [comment]
> Would it work if you change this line
> https://github.com/mar10/pyftpsync/blob/d71f347e63ab1f2bfeb922966f08f28ac2031a06/ftpsync/ftp_target.py#L84
> 
> to
> 
> ```python
>  self.ftp = ftplib.FTP(encoding=self.encoding)
> ```
> 
> ?

Its helped!
Now it successfully connecting to a server and read file structure.

But now i get another error message 

```
Traceback (most recent call last):
  File "/media/data_2/untitled6/Sync_FTP.py", line 26, in <module>
    s.run()
  File "/media/data_2/untitled6/ftpsync/synchronizers.py", line 1251, in run
    res = super(DownloadSynchronizer, self).run()
  File "/media/data_2/untitled6/ftpsync/synchronizers.py", line 833, in run
    res = super(BiDirSynchronizer, self).run()
  File "/media/data_2/untitled6/ftpsync/synchronizers.py", line 209, in run
    res = self._sync_dir()
  File "/media/data_2/untitled6/ftpsync/synchronizers.py", line 591, in _sync_dir
    handler(pair)
  File "/media/data_2/untitled6/ftpsync/synchronizers.py", line 857, in on_copy_remote
    self._copy_recursive(self.remote, self.local, remote_entry)
  File "/media/data_2/untitled6/ftpsync/synchronizers.py", line 329, in _copy_recursive
    dest.mkdir(dir_entry.name)
  File "/media/data_2/untitled6/ftpsync/targets.py", line 455, in mkdir
    os.mkdir(path)
```

**FileExistsError: [Errno 17] File exists: '/media/data_2/ftpSync'**

i try change code to

```
    def mkdir(self, dir_name):
        self.check_write(dir_name)
        path = normpath_url(join_url(self.cur_dir, dir_name))
        if not os.path.exists(path):
            os.mkdir(path)
```
but in this case it try create this folder in a infinite loop

I tried on windows and linux machine with the same outcome

**Comment by vgdh** [comment]
I'm stuck
